stages:
  - sync

sync_git:
  stage: sync
  script:
    - git clone git@github.com:sagavax/minecraft.git
    - cd Tsagavax/minecraft
    - git pull origin main
    - # Tvoje ďalšie príkazy alebo operácie