name: Deploy to Webhosting

on:
  push:
    branches:
      - main  # Automatické nasadenie po pushnutí na "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to SFTP Server
        uses: appleboy/scp-action@master
        with:
          host: www.tmisura.sk  # Alebo IP 37.9.175.197
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22  # SFTP používa port 22
          source: "./*"  # Nasadenie všetkých súborov v repozitári
          target: "/sub/minecraft/"  # Cieľová cesta na serveri
